// Code generated by apbr generate. DO NOT EDIT.
// versions:
// 	apbr generate v1.2

//go:build !codeanalysis

package model

import "github.com/google/uuid"

type Oauth2Provider struct {
	Id                    *uuid.UUID                     `json:"id,omitempty"`
	DefaultScopes         []string                       `json:"defaultScopes,omitempty"`
	Name                  string                         `json:"name,omitempty"`
	AuthUrl               string                         `json:"authUrl,omitempty"`
	TokenUrl              string                         `json:"tokenUrl,omitempty"`
	UserInfoUrl           string                         `json:"userInfoUrl,omitempty"`
	UserInfoExtractConfig *Oauth2ProviderUserInfoExtract `json:"userInfoExtractConfig,omitempty"`
	Version               int32                          `json:"version,omitempty"`
}

func (s Oauth2Provider) GetId() *uuid.UUID {
	return s.Id
}
func (s Oauth2Provider) GetDefaultScopes() []string {
	return s.DefaultScopes
}
func (s Oauth2Provider) GetName() string {
	return s.Name
}
func (s Oauth2Provider) GetAuthUrl() string {
	return s.AuthUrl
}
func (s Oauth2Provider) GetTokenUrl() string {
	return s.TokenUrl
}
func (s Oauth2Provider) GetUserInfoUrl() string {
	return s.UserInfoUrl
}
func (s Oauth2Provider) GetUserInfoExtractConfig() *Oauth2ProviderUserInfoExtract {
	return s.UserInfoExtractConfig
}
func (s Oauth2Provider) GetVersion() int32 {
	return s.Version
}

type Oauth2ProviderUserInfoExtract struct {
	Username *string `json:"username,omitempty"`
}

func (s Oauth2ProviderUserInfoExtract) GetUsername() *string {
	return s.Username
}
