// Code generated by apbr generate. DO NOT EDIT.
// versions:
// 	apbr generate v1.2

//go:build !codeanalysis

package model

import (
	"github.com/apibrew/apibrew/pkg/abs"
	"github.com/apibrew/apibrew/pkg/formats/unstructured"
	"github.com/apibrew/apibrew/pkg/model"
	"github.com/apibrew/apibrew/pkg/types"
	"google.golang.org/protobuf/types/known/structpb"
)

import "github.com/google/uuid"

type Oauth2RequestMapper struct {
}

func NewOauth2RequestMapper() *Oauth2RequestMapper {
	return &Oauth2RequestMapper{}
}

var Oauth2RequestMapperInstance = NewOauth2RequestMapper()

func (m *Oauth2RequestMapper) New() *Oauth2Request {
	return &Oauth2Request{}
}

func (m *Oauth2RequestMapper) ResourceIdentity() abs.ResourceIdentity {
	return abs.ResourceIdentity{
		Namespace: "sso",
		Name:      "Oauth2Request",
	}
}

func (m *Oauth2RequestMapper) ToRecord(oauth2Request *Oauth2Request) *model.Record {
	var rec = &model.Record{}
	rec.Properties = m.ToProperties(oauth2Request)
	return rec
}

func (m *Oauth2RequestMapper) FromRecord(record *model.Record) *Oauth2Request {
	return m.FromProperties(record.Properties)
}

func (m *Oauth2RequestMapper) ToProperties(oauth2Request *Oauth2Request) map[string]*structpb.Value {
	var properties = make(map[string]*structpb.Value)

	var_Id := oauth2Request.Id

	if var_Id != nil {
		var var_Id_mapped *structpb.Value

		var var_Id_err error
		var_Id_mapped, var_Id_err = types.ByResourcePropertyType(model.ResourceProperty_UUID).Pack(*var_Id)
		if var_Id_err != nil {
			panic(var_Id_err)
		}
		properties["id"] = var_Id_mapped
	}

	var_RedirectUrl := oauth2Request.RedirectUrl

	if var_RedirectUrl != nil {
		var var_RedirectUrl_mapped *structpb.Value

		var var_RedirectUrl_err error
		var_RedirectUrl_mapped, var_RedirectUrl_err = types.ByResourcePropertyType(model.ResourceProperty_STRING).Pack(*var_RedirectUrl)
		if var_RedirectUrl_err != nil {
			panic(var_RedirectUrl_err)
		}
		properties["redirectUrl"] = var_RedirectUrl_mapped
	}

	var_Config := oauth2Request.Config

	if var_Config != nil {
		var var_Config_mapped *structpb.Value

		var_Config_mapped = structpb.NewStructValue(&structpb.Struct{Fields: Oauth2ConfigMapperInstance.ToProperties(var_Config)})
		properties["config"] = var_Config_mapped
	}

	var_Version := oauth2Request.Version

	var var_Version_mapped *structpb.Value

	var var_Version_err error
	var_Version_mapped, var_Version_err = types.ByResourcePropertyType(model.ResourceProperty_INT32).Pack(var_Version)
	if var_Version_err != nil {
		panic(var_Version_err)
	}
	properties["version"] = var_Version_mapped
	return properties
}

func (m *Oauth2RequestMapper) FromProperties(properties map[string]*structpb.Value) *Oauth2Request {
	var s = m.New()
	if properties["id"] != nil && properties["id"].AsInterface() != nil {

		var_Id := properties["id"]
		val, err := types.ByResourcePropertyType(model.ResourceProperty_UUID).UnPack(var_Id)

		if err != nil {
			panic(err)
		}

		var_Id_mapped := new(uuid.UUID)
		*var_Id_mapped = val.(uuid.UUID)

		s.Id = var_Id_mapped
	}
	if properties["redirectUrl"] != nil && properties["redirectUrl"].AsInterface() != nil {

		var_RedirectUrl := properties["redirectUrl"]
		val, err := types.ByResourcePropertyType(model.ResourceProperty_STRING).UnPack(var_RedirectUrl)

		if err != nil {
			panic(err)
		}

		var_RedirectUrl_mapped := new(string)
		*var_RedirectUrl_mapped = val.(string)

		s.RedirectUrl = var_RedirectUrl_mapped
	}
	if properties["config"] != nil && properties["config"].AsInterface() != nil {

		var_Config := properties["config"]
		var_Config_mapped := Oauth2ConfigMapperInstance.FromProperties(var_Config.GetStructValue().Fields)

		s.Config = var_Config_mapped
	}
	if properties["version"] != nil && properties["version"].AsInterface() != nil {

		var_Version := properties["version"]
		val, err := types.ByResourcePropertyType(model.ResourceProperty_INT32).UnPack(var_Version)

		if err != nil {
			panic(err)
		}

		var_Version_mapped := val.(int32)

		s.Version = var_Version_mapped
	}
	return s
}

func (m *Oauth2RequestMapper) ToUnstructured(oauth2Request *Oauth2Request) unstructured.Unstructured {
	var properties unstructured.Unstructured = make(unstructured.Unstructured)
	properties["type"] = "sso/Oauth2Request"

	var_Id := oauth2Request.Id

	if var_Id != nil {
		var var_Id_mapped interface{}

		var_Id_mapped = var_Id.String()
		properties["id"] = var_Id_mapped
	}

	var_RedirectUrl := oauth2Request.RedirectUrl

	if var_RedirectUrl != nil {
		var var_RedirectUrl_mapped interface{}

		var_RedirectUrl_mapped = *var_RedirectUrl
		properties["redirectUrl"] = var_RedirectUrl_mapped
	}

	var_Config := oauth2Request.Config

	if var_Config != nil {
		var var_Config_mapped interface{}

		var_Config_mapped = Oauth2ConfigMapperInstance.ToUnstructured(var_Config)
		properties["config"] = var_Config_mapped
	}

	var_Version := oauth2Request.Version

	var var_Version_mapped interface{}

	var_Version_mapped = var_Version
	properties["version"] = var_Version_mapped

	return properties
}
