// Code generated by apbr generate. DO NOT EDIT.
// versions:
// 	apbr generate v1.2

//go:build !codeanalysis

package model

import "github.com/google/uuid"
import "time"

type Oauth2Identity struct {
	Id        *uuid.UUID               `json:"id,omitempty"`
	Username  string                   `json:"username,omitempty"`
	Details   interface{}              `json:"details,omitempty"`
	Config    *Oauth2Config            `json:"config,omitempty"`
	Version   int32                    `json:"version,omitempty"`
	AuditData *Oauth2IdentityAuditData `json:"auditData,omitempty"`
}

func (s Oauth2Identity) GetId() *uuid.UUID {
	return s.Id
}
func (s Oauth2Identity) GetUsername() string {
	return s.Username
}
func (s Oauth2Identity) GetDetails() interface{} {
	return s.Details
}
func (s Oauth2Identity) GetConfig() *Oauth2Config {
	return s.Config
}
func (s Oauth2Identity) GetVersion() int32 {
	return s.Version
}
func (s Oauth2Identity) GetAuditData() *Oauth2IdentityAuditData {
	return s.AuditData
}

type Oauth2IdentityAuditData struct {
	CreatedBy *string    `json:"createdBy,omitempty"`
	UpdatedBy *string    `json:"updatedBy,omitempty"`
	CreatedOn *time.Time `json:"createdOn,omitempty"`
	UpdatedOn *time.Time `json:"updatedOn,omitempty"`
}

func (s Oauth2IdentityAuditData) GetCreatedBy() *string {
	return s.CreatedBy
}
func (s Oauth2IdentityAuditData) GetUpdatedBy() *string {
	return s.UpdatedBy
}
func (s Oauth2IdentityAuditData) GetCreatedOn() *time.Time {
	return s.CreatedOn
}
func (s Oauth2IdentityAuditData) GetUpdatedOn() *time.Time {
	return s.UpdatedOn
}
